name: release-solution
# convert solution to managed (using a build PowerPlatform environment for the conversion)
# upload the solution to the GitHub artifacts and deploy to the PROD environment
on:
  workflow_dispatch:
    inputs: 
      solution_name:
        description: 'The solution name.'
        type: string
        required: true
        default: PermitManagement
      build_environment_url:
        description: 'build environment url.'
        type: string
        required: true
        default: https://orge62b6114.crm.dynamics.com/     
      release_environment_url: 
        description: 'release environment url.'
        type: string
        required: true
        default: https://org5e3579fa.crm17.dynamics.com/     

env:
  CLIENT_ID: '8dd637f1-d620-4c73-8f19-156db61cb616'
  TENANT_ID: '38ed5bef-40af-433f-b790-23c538ecf42a'
  SOLUTION_SHIPPING_FOLDER: out/ship/
  SOLUTION_OUTBOUND_FOLDER: out/solutions/
  SOLUTION_SOURCE_FOLDER: solutions/
  SOLUTION_RELEASE_FOLDER: out/release

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{ env.SOLUTION_SOURCE_FOLDER }}/${{ inputs.solution_name }}
        solution-file: ${{ env.SOLUTION_OUTBOUND_FOLDER }}/${{ inputs.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{inputs.build_environment_url }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.APP_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-file: ${{ env.SOLUTION_OUTBOUND_FOLDER }}/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{ inputs.build_environment_url }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.APP_SECRET }} 
        tenant-id: ${{ env.TENANT_ID }}
        solution-name: ${{ inputs.solution_name }}
        managed: true
        solution-output-file: ${{ env.SOLUTION_SHIPPING_FOLDER }}/${{ inputs.solution_name }}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.SOLUTION_SHIPPING_FOLDER}}/

  release-managed:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ env.SOLUTION_RELEASE_FOLDER }}

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{ inputs.release_environment_url }}
        app-id: ${{ env.CLIENT_ID }}
        client-secret: ${{ secrets.APP_SECRET }}
        tenant-id: ${{ env.TENANT_ID }}
        solution-file: ${{ env.SOLUTION_RELEASE_FOLDER }}/${{ inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true
